### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JakubBizewski** [DarkMuffinJoe/Offerum#1]
- [x] Security (Register and login)
- [ ] Offer CRUD
  - [x] Offer list
  - [x] Add form
  - [x] My offers tab
  - [x] Edit form
  - [x] Delete
  - [x] Offer details
  - [x] Offer list pagination
  - [x] HTML Editor for better offer descriptions (Quill, CKEditor)
  - [x] Offer image (will be used for example in offer list)
  - [x] Delivery type
  - [x] Item condition
  - [x] Better offer list visuals
  - [ ] Better offer details visuals
  - [ ] Slug
- [x] Offer categories
- [x] Filtering offers
- [x] Additional user information
  - [x] My information / My profile tab
  - [x] User public profile (with his offers, information etc.)
  - [x] Phone number
  - [x] Address
- [ ] Better user profile visuals
- [ ] Marking offers as interesting
  - [ ] List with offers marked as interesting
  - [ ] Number of people who marked an offer as interesting (?)
- [ ] Admin panel / additional options for admin
